### ISSUE TITLE
Fix select for coding based question

### ISSUE THREAD

**Issue by ir4y** [beda-software/sdc-ide#40]
If you define a choice question with Coding in answerOption it doesn't work.

```
      - text: Gender
        type: choice
        linkId: gender
        required: true
        answerOption:
          - value:
              Coding:
                code: male
                display: Male
          - value:
              Coding:
                code: female
                display: Female
```
