### ISSUE TITLE
Fix `exists` operator for boolean question types

### ISSUE THREAD

**Issue by vesnushka** [beda-software/sdc-ide#60]
`Exists` operator is not applied for boolean question types

```yaml
item:
  - text: Question 1
    type: boolean
    linkId: question1
  - text: Question 2
    linkId: question2
    enableWhen:
      - answer:
          boolean: false
        operator: exists
        question: question1
```
